### ISSUE TITLE
Outputting to JSON

### ISSUE THREAD

**Issue by javahemans** [JonathanVusich/pcpartpicker#37]
Hey mate, 

I had a quick question... I am not a python programmer. I managed to get your package running and outputting the data in a docker container...

The problem is, it is printing in a format that is not CSV or even JSON.

My docker script: 
```docker
FROM python:3

WORKDIR /usr/src/app

RUN pip install pcpartpicker

COPY . .

CMD [ "python", "./parts.py" ]

```
My python file: 

```python
from pcpartpicker import API

api = API()

all_data = api.retrieve_all()

# Need Your help here... so it print in JSON format instead of normal format
print(all_data) 
```

If I get it to print in JSON then I can pipe it to any file with `part.py > all-data.json`

Do you know how can I get it to print the `print(api.retrieve_all())` in JSON format?

**Comment by javahemans** [comment]
Reading your code further sounds like you returning `Dict[str, List]` type in `retrieve_all()` so I have to find a way to parse that type to JSON...

**Comment by javahemans** [comment]
I feel like I need to know more about python data types and libraries to turn `Dict[str, List]` to `JSON` or `CSV` format.

I appreciate if you could add a function to your api like `toJSON`, `toCSV` that accepts `Dict[str, List]` and returns a string that is the JSON or CSV 

I'm sure everyone would appreciate it as well 😀

**Comment by JonathanVusich** [comment]
All of the part data is returned as dataclass instances. Those should be JSON serializable using the `json.dumps` function found in the stdlib.

**Comment by JonathanVusich** [comment]
Are you trying to work with the data outside of Python?

**Comment by javahemans** [comment]
yes exactly... I wanted to use your script to take the data in JSON format... then transform it, do some pre-processing and use it in other languages or ....

**Comment by javahemans** [comment]
I tried `json.dump` doesn't seem to help much

**Comment by JonathanVusich** [comment]
https://stackoverflow.com/questions/51286748/make-the-python-json-encoder-support-pythons-new-dataclasses

**Comment by javahemans** [comment]
I get `TypeError: Object of type Money is not JSON serializable`. Is that because you have used `from moneyed import Money` library in [part.py](https://github.com/JonathanVusich/pcpartpicker/blob/master/pcpartpicker/parts.py) ??

**Comment by JonathanVusich** [comment]
I would say that is quite likely. You could probably add another check to the custom JSON encoder above to transform those Money instances into JSON as well. Something like this (untested):

```python
import dataclasses, json
from moneyed import Money

class EnhancedJSONEncoder(json.JSONEncoder):
        def default(self, o):
            if dataclasses.is_dataclass(o):
                return dataclasses.asdict(o)
            if isinstance(o, Money):
                return o.__dict__()
            return super().default(o)

json.dumps(foo, cls=EnhancedJSONEncoder)
```

**Comment by JonathanVusich** [comment]
This does seem like a useful feature to add, now that you have brought up these issues. I'll consider adding it to the API.

**Comment by javahemans** [comment]
I got the following error `TypeError: 'dict' object is not callable`. I modified a little bit, to return nothing to make it work for now as  I don't mind the price field being `null` in my case. 

Its still better than spending heaps of time at Stackoverflow while I don't even know python syntax and capabilities.... 🤦‍♂️
```python
            if isinstance(o, Money):
                return 
```

I'm definitely agree with you about CSV vs JSON....  👍

**Comment by JonathanVusich** [comment]
Version 2.2.0 will have this updated functionality.
