### ISSUE TITLE
Scrape data from PCPartPicker List

### ISSUE THREAD

**Issue by andymanic** [JonathanVusich/pcpartpicker#46]
Got a question - can this API scrape data like current price of a PC Part Picker list? I did my best to look around and see if it was supported but couldn't see anything. Is that supported?

**Comment by ZachSand** [comment]
It's not natively supported by the API. The API uses the data that resides in https://jonathanvusich.github.io/pcpartpicker-scraper/ as seen in https://github.com/JonathanVusich/pcpartpicker/blob/master/pcpartpicker/scraper.py.

**Comment by JonathanVusich** [comment]
Yes, @ZachSand is correct. The reason for this is to avoid sending a ton of traffic to pcpartpicker's web servers and potentially getting flagged as a bot and banned.
