### ISSUE TITLE
What is the time period of the snap shot?

### ISSUE THREAD

**Issue by ti-lei** [JonathanVusich/pcpartpicker#57]
HI i just come across this wonderful tool,however I check the data from your snapshot and the website. it's a bit different.
And another quick question.
I saw the issue **damageboy** propose at the pcpartpicker-scraper repo, he mentioned the site:http://pcpartspicker.houmus.org/us/memory.json
is the json file from the original website or it is sorted out by him??
Thank you

**Comment by JonathanVusich** [comment]
Yes, it has been a little while since I have grabbed an updated snapshot.

That specific JSON mentioned in the issue is the product of the scraper after it has created a snapshot.

**Comment by ti-lei** [comment]
hi i've tried to run the main.py in pcpartpicker-scraper in windows, but it failed. what's your environment for running this?

**Comment by JonathanVusich** [comment]
I believe you need chromedriver installed plus whatever other dependencies are listed in the requirements file.

**Comment by thedarkwriter** [comment]
This is a great tool, and after I wrote everything to use it I just realized that it's not actively pulling the stock list !!!!

Is it safe to assume that these snapshots are only updated occasionally @JonathanVusich and there is no intention to query PcPartPicker directly?

**Comment by JonathanVusich** [comment]
@thedarkwriter Yes, this API is designed to pull from a cache since always directly scraping PCPartPicker is problematic for a variety of reasons. I would like to set up continuous integration to have this done on a regular basis, but I have just not found the time to get it set up and deployed.

**Comment by mfeinst** [comment]
Hey Jonathan, any chance you'd have the time to run a quick update so newer parts are included?

**Comment by JonathanVusich** [comment]
@mfeinst Sure. I am still working on getting an API hosted to automate all of this stuff but I'll try to get one done soon.
