### ISSUE TITLE
Is there any way to check compatibility between parts?

### ISSUE THREAD

**Issue by MobCode100** [JonathanVusich/pcpartpicker#60]

**Comment by Morgan-Potter** [comment]
is this a feature? would be useful

**Comment by MobCode100** [comment]
One way is, to manually scrap pcpartpicker data. Do you want me to open this issue back? I don't think the developer is still actively maintaining this repo.

**Comment by Morgan-Potter** [comment]
nah its all good, I was just wondering if you found a solution. I'll probably go ahead and scrape it manually

**Comment by MobCode100** [comment]
Unfortunately, I don't find any other way than that for pcpartpicker.com. If you decide to manually scrap from the website, you'll be handling with millions of combination of parts and It'll be a very tedious brute force way.

Another challenge is that pcpartpicker has it's anti scraping technology, you can use undetected chrome driver, but based on my experience, can only scrape for 20-30 mins then the 'are you human' captcha will show up. You might have to track the progress of the scraping process for continuation.

**Comment by Morgan-Potter** [comment]
Yeah thanks for the info. For my application I only really need the cpu socket to check compatibility so I may just use a different dataset for that. Probably easier and faster than scraping the whole thing from scratch

**Comment by MobCode100** [comment]
I see, in my case i wanted to use the pcpartpicker compatibility checker for a pc build. No problem, I wish the best for you, good luck 👍.
